### ISSUE TITLE
No examples folder

### ISSUE THREAD

**Issue by prestonzen** [RasaHQ/rasa-action-examples#1]
I don't know if it's just me or if anyone else doesn't see the examples folder the README references.

**Comment by sara-tagger** [comment]
Thanks for the issue, @TyDunn will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by TyDunn** [comment]
@prestonzen I don't see it either. Any ideas @koaning?

**Comment by koaning** [comment]
This repo is very much work in progress, but I'll add an example right away!
